# Generated by Django 4.2.2 on 2023-06-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='no_of_guests',
            field=models.IntegerField(),
        ),
    ]
